### ISSUE TITLE
이메일 인증

### ISSUE THREAD

**Issue by jaewooMaeng** [HyunSangHan/meeting-frontend#10]
일단 AWS의 SNS 서비스 사용

**Comment by HyunsangHan** [comment]
Django의 기본 기능을 활용하는 것도 고려하기

@choiyeonseok 참고자료있으면 부탁해요~

**Comment by jaewooMaeng** [comment]
일단은 feature/email 이라는 브랜치에 대략적인 흐름의 뼈대는 잡아놨습니다.
하지만 현재 안되는 부분이
-> FBV를 활용했을 때 request.data에 오는 정보가 계속 null로 뜬다는 문제
-> 일단 우회하는 방법으로 짜놨지만 SMTP 서버(?)라는 것을 돌리고 있어야 실제로 메일이 가는 것으로 이해했는데
(@choiyeonseok 혹시 아는 부분이 있나요? - 예전에 django에서 email 보냈을 때 실제로 email이 도착했었나요)

*현재 front에서 /email이라고 치고 이메일 창으로 갈 수 있게 해두었습니다.

**Comment by jaewooMaeng** [comment]
> 일단은 feature/email 이라는 브랜치에 대략적인 흐름의 뼈대는 잡아놨습니다.
> 하지만 현재 안되는 부분이
> -> FBV를 활용했을 때 request.data에 오는 정보가 계속 null로 뜬다는 문제
> -> 일단 우회하는 방법으로 짜놨지만 SMTP 서버(?)라는 것을 돌리고 있어야 실제로 메일이 가는 것으로 이해했는데
> (@choiyeonseok 혹시 아는 부분이 있나요? - 예전에 django에서 email 보냈을 때 실제로 email이 도착했었나요)
> 
> *현재 front에서 /email이라고 치고 이메일 창으로 갈 수 있게 해두었습니다.

FBV관련 문제는 그냥 REST를 사용하는 편으로 해결하였습니다!
