### ISSUE TITLE
일괄반영 API콜 구현

### ISSUE THREAD

**Issue by HyunsangHan** [HyunSangHan/meeting-frontend#27]
- 개개인+실시간이 아닌, 정해진 시간에 콜되어야 할 API 구현
  * 참고: 커트라인 넣는 API콜은, 일괄반영이 아니라 한 인스턴스를 PATCH하는 용도라 좀 역할이 애매할 수 있는데, 이것도 '정해진 시간'에 콜되어야 할 API이므로 재우담당입니다.

@choiyeonseok @HyunSangHan 여기에 필요한 State들 댓글로 요청합시다.

**Comment by HyunsangHan** [comment]
저는 없는 것 같네요. 아마도 **절대시간**에 맞춰서 API를 콜 or 화면 refresh하는 게 @qwerty98765 @choiyeonseok @HyunSangHan 저희 모두의 숙제인 것 같습니다.

**Comment by c-yeonwoo** [comment]
저도 일단 없는 것 같습니다. refresh 된 API로 렌더하면 될것같네요 
절대시간 맞추는건 구글링으로 한번 알아보겠습니다.
