### ISSUE TITLE
cutline이 생성된 후 join 취소 혹은 회원탈퇴하는 경우

### ISSUE THREAD

**Issue by tyj9327** [HyunSangHan/meeting-frontend#29]
커트라인이 생성되기 전에는 별 문제가 없는데, 

- 커트라인이 생성된 후 매칭이 진행되는 도중에 한 팀이 빠지면 빠르게 후순위 팀에 기회를 주어야할지? 
- 기회가 주어진다면 어떤 방식으로 주어야 지체 없이 서비스가 가능할지? (알림 방식, 강제 셔플 참여 등)
- 커트라인을 두 성별 중 수가 적은 쪽이 가장 큰 랭크로 하는 것이 옳은 것인지? (후순위 팀이 없게 됨)
- 커트라인 선정 방식을 바꾼다면 어떻게 바꿀지 

에 대해 논의가 이루어져야 할 것 같습니다.

**Comment by HyunsangHan** [comment]
제 의견 드려봅니다.

커트라인을 정하고나면, 커트라인 기준으로 In/Out을 판별해서, In인 사람만 매칭 페이지에 들어오고, Out인 사람은 못들어오게 막는 걸로 작업중인데요. 후순위팀에게 기회를 주면, 사용자 입장에서도/운영및개발자 입장에서도 서비스가 좀 복잡해지지 않을까 싶습니다. 알림 줘서 입장도 시켜야 할 테고, 내부로직도 그렇고.. 저는 커트라인으로 짜르고 나면 기회는 더 주지 않는 게 낫지 않을까 싶네요.

더구나, 후순위 팀을 남겨놓기 위해서 매번 커트라인을 임의로 더 축소시키게 되면 사용자입장에서도 좋은 게 아닐 것 같고요. 예외가 발생하지 않도록 하기 위해 후순위 팀을 많이 남겨두면 매칭이 줄어들고, 후순위 팀을 최소화하면 예외가 발생하게 되므로 trade-off가 발생하는 상황으로 보입니다. 그렇게 하는 것보다는 차라리, 커트라인은 기존처럼 정하되 중간에 이탈자가 발생하면 is_matched=False인 사람 중 맨 뒷 등수의 사람에게 "아쉽지만 여기까지"인 것으로 자르는 게, 예외없이 진행시킬 수 있는 로직이 될 것 같습니다.

**Comment by tyj9327** [comment]
그렇다면 만약 남자팀에서 취소자가 발생한 경우 여자팀 중 아직 매칭이 되지 않은 팀 중 마지막 랭크인 팀은 셔플 도중에 기회를 잃는다는 말씀이신가요?

**Comment by HyunsangHan** [comment]
네, 어쩔 수 없지만 그게 피해를 최소화하는 방법이 아닐까 하는 생각입니다~
@qwerty98765 @choiyeonseok 의견주세요

**Comment by HyunsangHan** [comment]
#30 에서 구현하여 Close
