### ISSUE TITLE
Pull Request 타이틀 정리

### ISSUE THREAD

**Issue by HyunsangHan** [HyunSangHan/meeting-frontend#74]
현재 PR의 타이틀을 보면, 관리가 제대로 되지 않고 있습니다.
아마 다들 바쁘기도 하고 해커톤 기한이 타이트해서 신경쓰기 어려웠던 부분이었을 텐데요.

기존 타이틀 중 브랜치명 그대로 PR 타이틀을 달아둔 사례를,
히스토리 관리 차원에서라도 PR 내용에 맞게 제목을 수정했으면 합니다.

각자 작성한 PR에 대해 타이틀 수정해주시고, 완료했다면 이 이슈에 댓글 달아주세요.

**Comment by tyj9327** [comment]
넵!
